services:
#  sbdocs:
#    image: sbdocs
#    build:
#      context: ./
#    container_name: sbdocs
#    environment:
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
  pgvector:
    image: 'pgvector/pgvector:pg16'
#    container_name: pgvector
    environment:
      - 'POSTGRES_DB=sbdocs'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'